"""
Document Guard — FastAPI Backend (FIXED VERSION)
- Safe JSON responses
- Stable ML output handling
- Frontend-compatible (/analyze + /verify-document)
"""

from fastapi import FastAPI, File, UploadFile, HTTPException
from fastapi.middleware.cors import CORSMiddleware
from fastapi.responses import JSONResponse
import uvicorn
import fitz
import json

from detector import DocumentAuthenticityDetector

app = FastAPI(title="Document Guard API", version="2.0.1")

# =========================
# CORS (FIXED FOR DEPLOYMENT)
# =========================
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],  # change to your frontend URL later
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

detector = DocumentAuthenticityDetector()

ACCEPTED_TYPES = {
    "image/jpeg",
    "image/png",
    "image/jpg",
    "application/pdf"
}

MAX_FILE_SIZE = 10 * 1024 * 1024  # 10MB


# =========================
# HEALTH CHECK
# =========================
@app.get("/health")
def health():
    return {"status": "ok"}


# =========================
# CORE FUNCTION (SAFE WRAPPER)
# =========================
def safe_json(data):
    """Ensure all numpy / objects are JSON serializable"""
    return json.loads(json.dumps(data, default=str))


def run_analysis(contents, filename, is_pdf_flag, pdf_text="", pdf_metadata=None):
    """
    Runs ML analysis safely and guarantees JSON output
    """
    if pdf_metadata is None:
        pdf_metadata = {}

    result = detector.analyze(
        contents,
        filename or "document",
        is_pdf=is_pdf_flag
    )

    # 🔥 FIX: ensure required keys exist
    result.setdefault("flags", [])
    result.setdefault("details", [])

    # -------------------------
    # PDF EXTRA CHECKS
    # -------------------------
    if is_pdf_flag:
        import base64
        b64 = base64.b64encode(contents).decode("utf-8")
        result["originalImage"] = f"data:image/png;base64,{b64}"

        # Fake keyword detection
        suspicious_text = ["template", "sample", "demo", "fake", "specimen"]
        found_text = [t for t in suspicious_text if t in pdf_text]

        if found_text:
            result["authenticity_score"] = max(0, result.get("authenticity_score", 100) - 60)
            result["verdict"] = "LIKELY FAKE"
            kw_str = ", ".join(found_text).upper()

            result["flags"].append(f"Fake keywords found: {kw_str}")
            result["details"].append({
                "technique": "PDF Text Analysis",
                "finding": f"Detected watermark keywords: {kw_str}",
                "severity": "high",
                "score": 10.0
            })

        # Metadata check
        suspicious_meta = ["fpdf", "tcpdf", "reportlab", "html2pdf"]
        producer = pdf_metadata.get("producer", "").lower()
        creator = pdf_metadata.get("creator", "").lower()

        found_meta = [m for m in suspicious_meta if m in producer or m in creator]

        if found_meta:
            result["authenticity_score"] = max(0, result.get("authenticity_score", 100) - 40)

            if result["authenticity_score"] < 45:
                result["verdict"] = "LIKELY FAKE"

            mb_str = ", ".join(found_meta)
            result["flags"].append(f"Generated by script engine: {mb_str}")
            result["details"].append({
                "technique": "PDF Metadata Analysis",
                "finding": f"Generated using {mb_str}",
                "severity": "high",
                "score": 20.0
            })

    return safe_json(result)


# =========================
# MAIN ENDPOINT (RECOMMENDED)
# =========================
@app.post("/analyze")
@app.post("/verify-document")
async def analyze_document(file: UploadFile = File(...)):
    try:
        # Validate file type
        if file.content_type not in ACCEPTED_TYPES:
            raise HTTPException(
                status_code=400,
                detail="Invalid file type. Upload PDF, JPG, or PNG."
            )

        contents = await file.read()

        # Validate size
        if len(contents) > MAX_FILE_SIZE:
            raise HTTPException(
                status_code=400,
                detail="File too large (max 10MB)."
            )

        pdf_text = ""
        pdf_metadata = {}
        is_pdf_flag = file.content_type == "application/pdf"

        # -------------------------
        # PDF Handling
        # -------------------------
        if is_pdf_flag:
            try:
                pdf_doc = fitz.open(stream=contents, filetype="pdf")

                if len(pdf_doc) == 0:
                    raise ValueError("Empty PDF")

                page = pdf_doc[0]
                pdf_text = page.get_text("text").lower()
                pdf_metadata = pdf_doc.metadata or {}

                pix = page.get_pixmap(dpi=150)
                contents = pix.tobytes("png")

                pdf_doc.close()

            except Exception as e:
                raise HTTPException(
                    status_code=400,
                    detail=f"PDF processing failed: {str(e)}"
                )

        # -------------------------
        # ML Analysis
        # -------------------------
        result = run_analysis(
            contents,
            file.filename,
            is_pdf_flag,
            pdf_text,
            pdf_metadata
        )

        return JSONResponse(content=result)

    except HTTPException as he:
        return JSONResponse(
            status_code=he.status_code,
            content={"success": False, "error": he.detail}
        )

    except Exception as e:
        return JSONResponse(
            status_code=500,
            content={"success": False, "error": str(e)}
        )


# =========================
# LOCAL RUN
# =========================
if __name__ == "__main__":
    uvicorn.run("main:app", host="0.0.0.0", port=8000)